server:
  port: ${API_GATEWAY_PORT:8081}

spring:
  application:
    name: api-gateway

#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user-servie/**
#          filters:
#            - RewritePath=/user/(?<path>.*), /$\{path}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  validSec: 300

serviceclient:
  secret: dGhpc3Byb2plY3Rpc2JpZw==