version: '3.8'

services:

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: reading
      MONGO_INITDB_ROOT_PASSWORD: isgood
    ports:
      - "27017:27017"

  discovery-service:
    image: readingisgood/discovery-service:latest
    container_name: discovery-service
    restart: always
    environment:
      EUREKA_SERVER_PORT: 8761
      EUREKA_SERVER_URL:  http://discovery-service:8761
    ports:
      - "8761:8761"
  api-gateway:
    image: readingisgood/api-gateway:latest
    container_name: api-gateway
    restart: always
    environment:
      API_GATEWAY_PORT: 8081
      EUREKA_SERVICE_URL:  http://discovery-service:8761
      USER_SERVICE_URL: http://user-service:8082/user
    ports:
      - "8081:8081"

  stock-service:
    image: readingisgood/stock-service:latest
    container_name: stock-service
    restart: always
    environment:
      STOCK_SERVICE_PORT: 8083
      EUREKA_SERVICE_URL:  http://discovery-service:8761
      MONGO_URL: mongo-db:27017
      USER_SERVICE_URL: http://user-service:8082/user
    ports:
      - "8083:8083"
  user-service:
    image: readingisgood/user-service:latest
    container_name: user-service
    restart: always
    environment:
      USER_SERVICE_PORT: 8082
      EUREKA_SERVICE_URL: http://discovery-service:8761
      MONGO_URL: mongo-db:27017
    ports:
      - "8082:8082"

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: reading
#      ME_CONFIG_MONGODB_ADMINPASSWORD: isgood
#      ME_CONFIG_MONGODB_URL: mongodb://reading:isgood@mongo:27017/