server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://reading:isgood@localhost:27017/
      database: readingisgood
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/


