server:
  port: ${EUREKA_SERVER_PORT:8761}
spring:
  application:
    name: discovery-service


eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}